import { readFileSync, writeFileSync } from 'node:fs';
import { themes } from '../src/theme/registry.ts';
import { themesCss } from '../src/theme/css.ts';
import { initScript } from '../src/theme/init.ts';

const header = '/* Generated by scripts/gen-themes.ts. Do not edit. */\n';
const outputs: Record<string, string> = {
  'src/styles/themes.css': header + themesCss(themes),
  'src/theme/init.generated.js': header + initScript(themes),
};

const check = process.argv.includes('--check');
let stale = false;
for (const [path, content] of Object.entries(outputs)) {
  const url = new URL(`../${path}`, import.meta.url);
  let current: string;
  try {
    current = readFileSync(url, 'utf8');
  } catch {
    current = '';
  }
  if (current === content) continue;
  if (check) {
    console.error(`${path} is stale; run npm run gen`);
    stale = true;
  } else {
    writeFileSync(url, content);
    console.log(`wrote ${path}`);
  }
}
if (stale) process.exit(1);
